### ISSUE TITLE
bug: Save fails when branch has slash

### ISSUE THREAD

**Issue by realjck** [michaelmsonne/AzureDevOpsBackupTool#1]
**Version:**

1.0.5.7

**Current behavior:**

During a backup, branches with slashes in their names generate errors and are not backed up (example with branch `feat/foobar`):

`Exception caught when trying to save file to disk: 'C:\saves\DD-MM-YYYY-(hh-mm)\project_repo_feat/foobar_blob.zip' - error: System.IO.DirectoryNotFoundException: Unable to find part of path 'C:\saves\DD-MM-YYYY-(hh-mm)\project_repo_feat/foobar_blob.zip'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)`

**Comment by michaelmsonne** [comment]
Hi @realjck,

Thanks for the report! 👍

I see, thats how Windows translate the path..

I will take a look at it ASAP and update the tool 😉

I will update you here in this issue.

Thanks again!

//Michael

**Comment by realjck** [comment]
Hi Michael,

I fixed the problem.
It's indeed related with the path translation.

My solution was quick to implement. I am able to make a pull request if you wish.

**Comment by michaelmsonne** [comment]
Yes it is quick to implement a fix for that path translation :)

How did you fix it - more to evaluate the fix? And sure, you are welcome to open a pull request also if it is.

**Comment by michaelmsonne** [comment]
Code changes pushed to main :)
