### ISSUE TITLE
bug: Mail restricted to secure connections

### ISSUE THREAD

**Issue by mhaymore** [michaelmsonne/AzureDevOpsBackupTool#16]
# Bug Report

**Current behavior:**
Emails to non SSL enabled SMTP servers fails.

> Sorry, we are unable to send email notification of your presence. Please try again! Error: System.Net.Mail.SmtpException: Server does not support secure connections.
>    at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
>    at System.Net.Mail.SmtpClient.GetConnection()
>    at System.Net.Mail.SmtpClient.Send(MailMessage message)
>    at AzureDevOpsBackup.Class.ReportSender.SendEmail(String serverAddress, String serverPort, String emailFrom, String emailTo, String emailStatusMessage, List`1 repoCountElements, List`1 repoItemsCountElements, Int32 repoCount, Int32 repoItemsCount, Int32 totalFilesIsBackupUnZipped, Int32 totalBlobFilesIsBackup, Int32 totalTreeFilesIsBackup, String outDir, String elapsedTime, Int32 errors, Int32 totalFilesIsDeletedAfterUnZipped, Int32 totalBackupsIsDeleted, String daysToKeep, String repoCountStatusText, String repoItemsCountStatusText, String totalFilesIsBackupUnZippedStatusText, String totalBlobFilesIsBackupStatusText, String totalTreeFilesIsBackupStatusText, String totalFilesIsDeletedAfterUnZippedStatusText, String letOverZipFilesStatusText, String letOverJsonFilesStatusText, String totalBackupsIsDeletedStatusText, Boolean useSimpleMailReportLayout, Boolean noAttatchLog, String isOutputFolderContainFilesStatusText, String isDaysToKeepNotDefaultStatusText, String startTime, String endTime, Boolean deletedFilesAfterUnzip, Boolean checkForLeftoverFilesAfterCleanup)

And terminal output nor log report failure

**Expected behavior:**

Requesting switch or config to allow sending to non-SSL enabled SMTP servers.

**Comment by michaelmsonne** [comment]
Thanks for the report! Will look into it and get back - have not tested this, as I have not a non secure SMTP server 😉

**Comment by michaelmsonne** [comment]
Hi @mhaymore ,

I have created a pre-release here you can test out :)

https://github.com/michaelmsonne/AzureDevOpsBackupTool/releases/tag/1.1.2.1

Let me hear if it works for you or not :)

**Comment by mhaymore** [comment]
@michaelmsonne I just tested it, and it worked great for me. No more errors, and the email was sent and received successfully. Thank you!

**Comment by michaelmsonne** [comment]
Nice to hear @mhaymore - I will puch it to main! Thanks for confirming it´s working 😎

No problem!

**Comment by michaelmsonne** [comment]
Official build is now here :)

https://github.com/michaelmsonne/AzureDevOpsBackupTool/releases/tag/1.1.2.1

Thanks for the bug reporting!
