### ISSUE TITLE
bug: Crash on heavy branches (~500MB)

### ISSUE THREAD

**Issue by realjck** [michaelmsonne/AzureDevOpsBackupTool#3]
# Bug Report

**Version:**

1.0.5.7

**Current behavior:**

Hello again,

After the fix I made for the previous ticket we were able to run the program to clone our Azure account.

However, I found myself confronted with a second problem, because we have a project which includes a very heavy branch (more than 500MB zipped), and therefore the reading of the buffer was interrupted silently after a certain amount of time (seems to be 60s), and produced an error at this line :

https://github.com/michaelmsonne/AzureDevOpsBackupTool/blob/6bea9b06a27f523c03e2e78f088b7b21009343a0/AzureDevOpsBackup/Program.cs#L505-L508

The error is that `data` is null, the program crashes at `data.length`

**Expected behavior:**

The program should continue on this exception, but it doesn't (at least in debug mode)

**Solution:**

So I first upgraded the RestSharp library to its latest version, and it now works a little better because there is no longer a timeout but an exception (`System.OutOfMemoryException`). This is noted by the program, and therefore no longer interrupts it. You can find this new branch here: https://github.com/realjck/AzureDevOpsBackupTool/tree/upgrade-restsharp

A priori, a good practice to correct this problem would be to use a DownloadStreamAsync as indicated on this thread: https://stackoverflow.com/questions/76346750/restsharp-downloaddata-out-of-memory-exception-in-net-app

I asked a more experienced colleague than me to look at this next week, we can tell you if we have made this fix and if it resolves our problem.

Thank you!

**Comment by michaelmsonne** [comment]
Nice find @realjck !

I had not so large project to test with, so this is a very nice finding!

It´s sounds right, and I will take a look at the code, and I will look forward to hear if it fixing it - else let me know, and I will be happy to help 😎

I will then say that my original code from here was much smaller to start with, so the code base is just bigger over time... And I had a cleanup on my to do..

Thanks again for your good input´s here! 👌

**Comment by michaelmsonne** [comment]
Hi @realjck,

Any news on the tests? 😉

It then, lets fix it.

**Comment by realjck** [comment]
Hi @michaelmsonne 

We changed the writing part of the blob and fixed the issue. This now works for very large repos.

I am preparing a pull request based on the latest version, I will send it today.

**Comment by michaelmsonne** [comment]
Nice to hear that @realjck - thanks for testing it, and fix it via the code change here!

I will merge it soon! 👍🙌

Thanks for your contribution!

**Comment by michaelmsonne** [comment]
It´s now merged, thanks for your collaboration about this bug @realjck 👌
