### ISSUE TITLE
feat: Add the ability to add an extra person to email to or multiple emails? 

### ISSUE THREAD

**Issue by tysonsearls** [michaelmsonne/AzureDevOpsBackupTool#9]
# Feature Request

**Describe the Feature Request**

Add the ability to add an extra person to email to or multiple emails? 

**Describe Preferred Solution**

Add and extra person to the arguments sent to application or to be able to add emails with a comma

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by michaelmsonne** [comment]
Hi @tysonsearls ,

Good idear :)

Thanks!

**Comment by michaelmsonne** [comment]
I have now this implemented in the upcomming v. of the tool - developed and tested here :)

Stay turned!

**Comment by michaelmsonne** [comment]
@tysonsearls released here with this add :)

https://github.com/michaelmsonne/AzureDevOpsBackupTool/releases/tag/1.1.0.0
